services:
  postgres:
    image: postgres:17
    container_name: postgres_jwtauth
    environment:
      POSTGRES_DB: jwtauthdb
      POSTGRES_USER: jwtauth_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jwtauth_user -d jwtauthdb" ]
      interval: 5s
      retries: 5

  vault:
    image: hashicorp/vault:1.18.0
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token-2026
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    command: server -dev
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 5s
      retries: 5

volumes:
  postgres_data: